export interface BookMarkContextDto {
    show: boolean,
    setShow: Function,
    isCardView: boolean,
    setIsCardView: Function,
    isEdit: boolean,
    setIsEdit: Function,
    selectedTab: string,
    setSelectedTab: Function,
    createBookMark: boolean,
    setCreateBookMark: Function,
    selectedId : string | null,
    setSelectedId: Function,
    search : string ,
    setSearch : Function,
    rows : string,
    setRows : Function,
    page : string,
    setPage : Function,
    status:string,
    setStatus:Function,
    openFilter : boolean,
    setOpenFilter : Function,
}