import './globals.css'
import { Inter } from 'next/font/google'
import ReduxProvider from './reduxProvider'
import SideBar from '../components/GlobalComponents/sideBar/SideBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <ReduxProvider>
        <body className={inter.className}>
          <div className='flex'>
            <SideBar />
            {children}
          </div>
        </body>
      </ReduxProvider>
    </html>
  )
}
