import './globals.css'
import { Inter } from 'next/font/google'
import ReduxProvider from './reduxProvider'
import SideBar from '../components/GlobalComponents/sideBar/SideBar'
import TabSection from '@/components/GlobalComponents/bottomTab/TabSection'
import ReactQueryProvider from './reactQueryProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <ReduxProvider>
        <ReactQueryProvider>
          <body className={inter.className}>
            <div className='flex w-full'>
              <SideBar />
              {/* <div className='flex w-full flex-col'> */}
              <div className='w-full  h-screen flex flex-col justify-between overflow-scroll '>
                {children}
                <TabSection />
              </div>
              {/* </div> */}
            </div>
          </body>
        </ReactQueryProvider>
      </ReduxProvider>
    </html>
  )
}
