import './globals.css'
import { Inter } from 'next/font/google'
import ReduxProvider from './reduxProvider'
import SideBar from '../components/GlobalComponents/sideBar/SideBar'
import TabSection from '@/components/GlobalComponents/bottomTab/TabSection'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <ReduxProvider>
        <body className={inter.className}>
          <div className='flex h-screen w-full'>
            <SideBar />
            <div className='h-screen w-full border border-red-900 flex flex-col justify-between overflow-scroll'>
              {children}
              <TabSection />
            </div>
          </div>
        </body>
      </ReduxProvider>
    </html>
  )
}
